-- Run in phpMyAdmin on database preisliste_db
-- This renames technical columns col_a..col_an to semantic names.

USE preisliste_db;

ALTER TABLE catalog_items
  CHANGE COLUMN col_a  TO materialpreis_metall VARCHAR(255),
  CHANGE COLUMN col_b  TO arbeitszeit VARCHAR(255),
  CHANGE COLUMN col_c  TO verlust VARCHAR(255),
  CHANGE COLUMN col_d  TO galvanik VARCHAR(255),
  CHANGE COLUMN col_e  TO furnituren_au_750_333 VARCHAR(255),
  CHANGE COLUMN col_f  TO furnituren_ag_925 VARCHAR(255),
  CHANGE COLUMN col_g  TO colorit VARCHAR(255),
  CHANGE COLUMN col_h  TO schnur VARCHAR(255),
  CHANGE COLUMN col_i  TO verschluesse_gg_wg VARCHAR(255),
  CHANGE COLUMN col_j  TO verschluesse_925 VARCHAR(255),
  CHANGE COLUMN col_k  TO verschluesse_edelstahl VARCHAR(255),
  CHANGE COLUMN col_l  TO stein_typ VARCHAR(255),
  CHANGE COLUMN col_m  TO stein_faktor VARCHAR(255),
  CHANGE COLUMN col_n  TO perle_typ VARCHAR(255),
  CHANGE COLUMN col_o  TO perle_faktor VARCHAR(255),
  CHANGE COLUMN col_p  TO furnituren_wg VARCHAR(255),
  CHANGE COLUMN col_q  TO zusatz_q VARCHAR(255),
  CHANGE COLUMN col_r  TO fixkosten_r VARCHAR(255),
  CHANGE COLUMN col_s  TO fixkosten_s VARCHAR(255),
  CHANGE COLUMN col_t  TO sonstiges_t VARCHAR(255),
  CHANGE COLUMN col_u  TO reparaturen VARCHAR(255),
  CHANGE COLUMN col_v  TO reparaturpreis VARCHAR(255),
  CHANGE COLUMN col_w  TO kalkulation_w VARCHAR(255),
  CHANGE COLUMN col_x  TO x_basis VARCHAR(255),
  CHANGE COLUMN col_y  TO y_aufgerundet VARCHAR(255),
  CHANGE COLUMN col_z  TO zwischenwert_z VARCHAR(255),
  CHANGE COLUMN col_aa TO aa_multiplikator VARCHAR(255),
  CHANGE COLUMN col_ab TO ab_vk_aufgerundet VARCHAR(255),
  CHANGE COLUMN col_ac TO spalte_ac VARCHAR(255),
  CHANGE COLUMN col_ad TO spalte_ad VARCHAR(255),
  CHANGE COLUMN col_ae TO spalte_ae VARCHAR(255),
  CHANGE COLUMN col_af TO spalte_af VARCHAR(255),
  CHANGE COLUMN col_ag TO spalte_ag VARCHAR(255),
  CHANGE COLUMN col_ah TO spalte_ah VARCHAR(255),
  CHANGE COLUMN col_ai TO spalte_ai VARCHAR(255),
  CHANGE COLUMN col_aj TO spalte_aj VARCHAR(255),
  CHANGE COLUMN col_ak TO spalte_ak VARCHAR(255),
  CHANGE COLUMN col_al TO spalte_al VARCHAR(255),
  CHANGE COLUMN col_am TO spalte_am VARCHAR(255),
  CHANGE COLUMN col_an TO spalte_an VARCHAR(255);
