-- Run in phpMyAdmin on database preisliste_db.
-- This renames legacy technical columns col_a..col_an to the current catalog_items names.
-- Use only on an old table that still has col_a..col_an.

USE preisliste_db;

ALTER TABLE catalog_items
  CHANGE COLUMN col_a  artikel_code VARCHAR(255),
  CHANGE COLUMN col_b  bild VARCHAR(255),
  CHANGE COLUMN col_c  ag_in_g VARCHAR(255),
  CHANGE COLUMN col_d  ag_incl_verlust VARCHAR(255),
  CHANGE COLUMN col_e  au_in_g VARCHAR(255),
  CHANGE COLUMN col_f  au_incl_verlust VARCHAR(255),
  CHANGE COLUMN col_g  zeit_in_h VARCHAR(255),
  CHANGE COLUMN col_h  artikel_zusatz VARCHAR(255),
  CHANGE COLUMN col_i  stueck_1 VARCHAR(255),
  CHANGE COLUMN col_j  steine_perlen_ek VARCHAR(255),
  CHANGE COLUMN col_k  steine_messe VARCHAR(255),
  CHANGE COLUMN col_l  artikel_2 VARCHAR(255),
  CHANGE COLUMN col_m  stueck_2 VARCHAR(255),
  CHANGE COLUMN col_n  furnituren_steine_ek VARCHAR(255),
  CHANGE COLUMN col_o  steine_messe_2 VARCHAR(255),
  CHANGE COLUMN col_p  plattierung_oxidation VARCHAR(255),
  CHANGE COLUMN col_q  schnur_2 VARCHAR(255),
  CHANGE COLUMN col_r  leer_1 VARCHAR(255),
  CHANGE COLUMN col_s  leer_2 VARCHAR(255),
  CHANGE COLUMN col_t  kategorie VARCHAR(255),
  CHANGE COLUMN col_u  subkategorie VARCHAR(255),
  CHANGE COLUMN col_v  artikelnr VARCHAR(255),
  CHANGE COLUMN col_w  artikel VARCHAR(255),
  CHANGE COLUMN col_x  ek VARCHAR(255),
  CHANGE COLUMN col_y  preis_stueck_ek VARCHAR(255),
  CHANGE COLUMN col_z  preis_paar_ek VARCHAR(255),
  CHANGE COLUMN col_aa vkstk_ek_2_5_ungerundet VARCHAR(255),
  CHANGE COLUMN col_ab preis_stueck_2_5 VARCHAR(255),
  CHANGE COLUMN col_ac paarpreis_vk_2_5_ungerundet VARCHAR(255),
  CHANGE COLUMN col_ad preis_paar_2_5 VARCHAR(255),
  CHANGE COLUMN col_ae beschreibung VARCHAR(255),
  CHANGE COLUMN col_af nochmals_artikel VARCHAR(255),
  CHANGE COLUMN col_ag vkstk_ek_2_3_ungerundet VARCHAR(255),
  CHANGE COLUMN col_ah preis_stueck_2_3 VARCHAR(255),
  CHANGE COLUMN col_ai vkpaar_ek_2_3_ungerundet VARCHAR(255),
  CHANGE COLUMN col_aj preis_paar_2_3 VARCHAR(255),
  CHANGE COLUMN col_ak reserve_1 VARCHAR(255),
  CHANGE COLUMN col_al reserve_2 VARCHAR(255),
  CHANGE COLUMN col_am reserve_3 VARCHAR(255),
  CHANGE COLUMN col_an reserve_4 VARCHAR(255);
